# Generated by Django 6.0.6 on 2026-06-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('avg_duration_minutes', models.PositiveIntegerField(default=15)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
