# Generated by Antigravity - Only adds MISSING columns

import datetime
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='end_time',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AddField(
            model_name='service',
            name='number_of_slots',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='service',
            name='start_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
