# Generated by Django 6.0.6 on 2026-06-09 06:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('slots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_hash', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('token_number', models.PositiveIntegerField()),
                ('citizen_name', models.CharField(max_length=150)),
                ('citizen_email', models.EmailField(max_length=254)),
                ('citizen_phone', models.CharField(blank=True, max_length=15)),
                ('is_walkin', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('booked', 'Booked'), ('called', 'Called'), ('served', 'Served'), ('no_show', 'No Show'), ('skipped', 'Skipped'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('counter_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('served_at', models.DateTimeField(blank=True, null=True)),
                ('payment_status', models.CharField(default='pending', max_length=20)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('call_attempts', models.PositiveSmallIntegerField(default=0)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('completion_sent', models.BooleanField(default=False)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='slots.slot')),
            ],
            options={
                'ordering': ['token_number'],
                'unique_together': {('slot', 'token_number')},
            },
        ),
    ]
