# Generated by Antigravity

import uuid
from django.db import migrations, models

def gen_uuid(apps, schema_editor):
    Token = apps.get_model('tokens', 'Token')
    for row in Token.objects.all():
        Token.objects.filter(pk=row.pk).update(unique_hash=uuid.uuid4())

class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='unique_hash',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='token',
            name='unique_hash',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
