# Generated by Antigravity

import uuid
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='unique_hash',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
