# Generated by Django 6.0.6 on 2026-06-05 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hour', models.PositiveSmallIntegerField()),
                ('total_capacity', models.PositiveIntegerField(default=10)),
                ('walkin_buffer', models.PositiveIntegerField(default=3)),
                ('is_blocked', models.BooleanField(default=False)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='services.service')),
            ],
            options={
                'unique_together': {('service', 'date', 'hour')},
            },
        ),
    ]
