# Generated by Django 6.0.6 on 2026-06-10 07:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_add_fields'),
        ('slots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='end_time',
            field=models.TimeField(default=datetime.time(10, 0)),
        ),
        migrations.AddField(
            model_name='slot',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slot',
            name='start_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AddField(
            model_name='slot',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('locked', 'Locked'), ('booked', 'Booked')], default='available', max_length=20),
        ),
        migrations.AlterModelOptions(
            name='slot',
            options={'ordering': ['date', 'start_time']},
        ),
        migrations.AlterUniqueTogether(
            name='slot',
            unique_together={('service', 'date', 'start_time')},
        ),
        migrations.RemoveField(
            model_name='slot',
            name='hour',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='is_blocked',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='total_capacity',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='walkin_buffer',
        ),
    ]
