# Generated by Django 6.0.6 on 2026-06-10 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0002_alter_slot_options_alter_slot_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='slot',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
